### ISSUE TITLE
cannot import name 'TEME'

### ISSUE THREAD

**Issue by pdelteil** [crr0tz-4-d1nn3r/HackASat2020#1]
I'm getting this error while trying to run the program.
```

from astropy.coordinates import TEME, ITRS, CartesianDifferential, CartesianRepresentation, EarthLocation, AltAz, Angle
ImportError: cannot import name 'TEME' from 'astropy.coordinates'
```

**Comment by crr0tz-4-d1nn3r** [comment]
I think there was an older version in the pip library.  To make things work, had to pull the source down and build. Here's the basic idea, but may want to read the docs: https://docs.astropy.org/en/stable/install.html#building-from-source
Run the following:
```
git clone --recursive git://github.com/astropy/astropy.git
```
cd into the repo's folder and run pip:
```
pip3 install .
```

**Comment by pdelteil** [comment]
It worked. Thanks a lot for your help.
